apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: denyreviewsv3handler
  namespace: service-graph
spec:
  compiledAdapter: denier
  params:
    status:
      code: 7
      message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: denyreviewsv3request
  namespace: service-graph
spec:
  compiledTemplate: checknothing
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denyreviewsv3
  namespace: service-graph
spec:
  match: source.labels["app"]=="productpage"
  actions:
  - handler: denyreviewsv3handler
    instances: [ denyreviewsv3request ]
